name: bookkursi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  draggable_fab: ^0.1.4
  dropdown_search: ^2.0.1
  flutter:
    sdk: flutter
  get: 4.6.1
  intl: ^0.17.0
  modal_bottom_sheet: ^2.0.0
  syncfusion_flutter_datepicker: ^19.4.52

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/

  uses-material-design: true
